### ISSUE TITLE
A Nudge in the Right Direction

### ISSUE THREAD

**Issue by Trasd** [radimitrov/CSharpShellApp#144]
I am new to C#, but I've been programming for years.  At this point, I'm just trying to build the simple Android native examples, but I cannot get them to compile.  I'm having 2 problems:

1. "//This example requires the 'Xamarin.Android GUI' option to be enabled" - what does this mean?  I cannot find an "option" to "enable" it anywhere.  I have a feeling that this leads to my second problem:
2. Whenever I try to compile one of the examples, like the dialobox, I always get this error: "The name 'Ui' does not exist in the current context"

I already know how to program Android with Java (I even have an app in Gaggle's store), but I want to learn C# and eventually get get away from native Android Java apps in favor of Unity games (I refuse to learn Kotlin as I already learned Java to program Android - it's not my fault (or Radostin's) Gaggle cannot make up their minds).  For now, though, I'd settle for writing apps with C#, I just cannot seem to get past the C# new-user Xamarin hump!  

For example, how do I find which libraries to use (which references they contain).  I tried searching the internet, but I am not finding reliable information on this type of data.

What is the best way to get started (I said new to C#,  but I should have said new to Xamarin as I have already learned C# basics)?

Any help will be rewarded with good apps and hopefully, fun games in the future!  LOL  Thanks in advance.

**Comment by radimitrov** [comment]
Ah, that error is my fault. The reference tags in the example project file are faulty. I'll fix it in a future update and remove the old comment on the top.
For now manually reference "Mono.Android.dll" and "NativeUiLib.dll"

**Comment by Trasd** [comment]
Radostin, that spent help as I have no idea how to reference them manually!

I added the references, then tried to add a "using" statement for them.  Remember, I'm trying to learn how to do this kind of thing and not knowing C# compounds the issue.

Play like you're instructing a kindergartener for now, until I "get" the setup!

**Comment by radimitrov** [comment]
Sorry about the faulty project. Leftovers from when I did major upgrades of this app. It's fixed for an update in a few hours.
DLL references are added from the left drawer. The app internally contains a lot of them but external ones can be added too. But that doesn't matter anymore in this case.

Also Xamarin.Android support is incomplete in this app due to the way Xamarin works.
So I'd suggest fiddling with Xamarin.Forms instead. More complete support and still GUI, but easier to get into. 
It also has XAML support - XML like GUI layout file.

When dealing with GUI Xamarin apps are very simply put C# with obscure "smart glue" binding to Java classes.
Same applies for Unity - it has Java GUI view and native API bindings. So the app doesn't support that - the generating and binding of Java.

Starting with console applications is easiest in case you're new to C# or programming in general.

**Comment by Trasd** [comment]
Radostin, by all means, concentrate on the core functionality of the app!  Details always come last, after major changes.  I'm not bothering to update my app because I gave up trying to keep up with Gaggle's unreasonable demands (if I wanted unrestricted control over how I use my devices, I would have went with iOS).

I will switch over to "Forms," then.  I noticed those examples (the ones I tried) compile fine (or are easy enough to figure out).  I assume I'll need to readjust when (IF) I write public consumption apps with Xarmarin, but I'll tackle that when (IF) it ever comes up.

I have learned C# basics (using C# Shell .NET IDE), but never ran into these issues.  Partly because my real learning and testing apps are done on a rooted Lollipop tablet.  So much easier than fighting Gaggle's new(er) restrictions.  I wanted to try Xarmarin so I can see more and better results with more complex apps.  So, thanks!  I'll learn C# Xarmarin Forms for now.

**Comment by radimitrov** [comment]
Yeah, this app was practically always intended for learning C# on the go. I'm still going to do some improvements in that area. But it also has a few fun toys like GUI support (useful for learning too) and making independent apps via APK. That last feature is soon getting axed by Giggle, so I agree with you here. Annoying workarounds for that are in the near future.

**Comment by Trasd** [comment]
Oh, trust me, I already read your posts on that and Gaggle's new policies!  I didn't know you needed the REQUEST_INSTALL_PACKAGES permission to bundle with an APK in your asset folder.  I don't understand why, but I've not tried creating a new, or bundling with an existing, APK (from an app itself).  Otherwise, you'd only need to remove the "ask the user to install" ability and dump the APK in Download or something so we could sideload it.

With the (3) options you came up with, I personally like the external APK sideload one.  That's how [Phone Profile](https://play.google.com/store/apps/details?id=sk.henrichg.phoneprofilesplus) did it and it works fine.  A few others have done it that way, too.

I did want to point out that Rhythm Software request the ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION permission in their "[Code Editor - Compiler & IDE](https://play.google.com/store/apps/details?id=com.rhmsoft.code)" and Gaggle approved it, if you wanted to try that route with your file management.

**Comment by radimitrov** [comment]
Not to bundle, just prompt install. Yes, without that permission you would just need to manually do that via a file manager. 30 additional seconds to do that, I guess? It's the APK embedding or downloading part of their rules that are a problem here. No APK template file - no APK export feature.

Surprising they approved full storage management for a programming app, but that app is basically only a code editor as far storage is considered. Limited in what it allows to be done locally.
C# Shell however can be used to run code that damages the file system somewhat, like a ZIP bomb. 
Or to flood the main storage with 50 trillion files. 

I might try for approval, but I think the chance of getting it is very low. 
Don't worry, that custom version I talked about in the new Google policies issue will have 2 flavors - package install and package install + full storage management. So that is coming back if people want it.

**Comment by Trasd** [comment]
Gotcha!  I thought you specifically said the app installation permission. I'll reread it when I get a chance.

It sounds like your solution is the best.  Screw Gaggle, just leave a simple version in the store for IAP purposes, then they should find their way here where they will learn about the sideloadable full function APK.

Try for the full storage access permission though, you never know.  One of the reasons I bout my new Lenovo (God I love it), besides that it hauls butt and full of bang for your buck, with no bloatware, etc., etc, is that it is fully rootable!  They don't care and, the make it easy (I mean a real root, too, not a rooted version sitting on top of a non-rooted version).

Lenovo Tab P11 Pro (TBJ706F), Qualcomm Snapdragon 730G 2.20 GHz [8 core], 128 GB Internal Storage, 6 GB RAM, running Android 11.  It's only like $400 USD.

**Comment by Trasd** [comment]
Thanks!
