### ISSUE TITLE
 Is it possible to add lib.so to the project

### ISSUE THREAD

**Issue by WithoutCoffeeBr** [radimitrov/CSharpShellApp#261]
I would like to remove this doubt since I did not find an alternative.

**Comment by radimitrov** [comment]
I will add the ability to automatically add .so files based on project folder structure even though that use is limited. Currently C# Shell takes .so files if a dependency has a "__AndroidNativeLibraries__.zip" resource.
To clarify it is impossible to add .so files at runtime due to Android dependency. This only works for an independent app / APK.

**Comment by WithoutCoffeeBr** [comment]
I understand, but it was just a question. Until I managed to find an alternative that would be to insert the .so manually.
