### ISSUE TITLE
Open Options for Permissions in example

### ISSUE THREAD

**Issue by Alisis33** [radimitrov/CSharpShellApp#355]
It would be useful if the permission example would include a code to open the options where the permissions could be switched on.

(I woul be happy for a examle for the old pre Maui code, because my codes still not work with the new version. A work still with the old cshell because of multiple issues.)

**Comment by radimitrov** [comment]
There is no such example because the pre MAUI version (Xamarin.Forms) automatically requested any declared permissions. 
This isn't applicable in the newer versions as detailed in the APK permissions section and the permissions example. Summary: Permissions can only be requested from Activity, however users often try to do that before it is open (MauiProgram.cs vs MainPage.cs).

**Comment by radimitrov** [comment]
As for opening the app setting and therefore permissions screen [this ](https://stackoverflow.com/questions/32822101/how-can-i-programmatically-open-the-permission-screen-for-a-specific-app-on-andr)is the way after Activity startup.
