### ISSUE TITLE
Entering problem

### ISSUE THREAD

**Issue by Agnefits** [radimitrov/CSharpShellApp#365]
I use google keyboard, and when I want to run a code that includes input method (ReadLine), it doesn't response with the enter key.
Also the whole code and compiling area are using password keyboard which make it difficult to enter the code and words.
Thank you very much, powerful team.

**Comment by radimitrov** [comment]
Can you provide more information on your configuration? Device, OS version, app version, settings.
Videos of the bugs would also be very helpful to accurately describe the behavior.

Yes, the code editor's input uses TextInputVisiblePassword to prevent IME's from attempting text composition logic/actions since that can be very problematic in code editors. Text composition can be enabled from the app settings at the possible cost of problems, but that removes the password flag.
What problems are you experiencing with it?

As for the console enter key not working - it should. I would need to see exactly what is happening there to be able to do more

**Comment by radimitrov** [comment]
I have added a flag that should remove the confirm button and a handler for this case if it is ignored.
