### ISSUE TITLE
Exporting apk crashes app due to full screen ads

### ISSUE THREAD

**Issue by Jooe20** [radimitrov/CSharpShellApp#371]
Suggestion : It will be great if exporting apks will be consuming code completion credits (ccr). The ccr may be 36, 72, or even more as loading ads instantly when exporting apk is very frustrating due to crashes. Thanks.

**Comment by radimitrov** [comment]
How often do crashes happen? The last 1 or 2 updates (v3.2.88) have an [SDK adjustment](https://developers.google.com/admob/android/optimize-initialization) to counter slowly loading ads that lockup the app. Statistics reports indicate this helps somewhat, but the problem persists. AdMob ANR's have been a [growing issue](https://groups.google.com/g/google-admob-ads-sdk/c/6LfTaInDGtU). Best case scenario is that this is being caused by bad and/or overly demanding ads that lock up the WebView they are trying to run in. In reports ANRs (freeze crashes) of the C# Shell app decrease relative to device RAM. Most of them are ads related.

I'm not sure there is any real solution since this requires fixes by Google they haven't done for years. Best I can do is recommend using the new "Quick deploy" feature when possible. 
Also does this only happen with exporting APKs or regular compilation too?

**Comment by Jooe20** [comment]
It only happens when exporting APKs but like you said, the current version 3.2.88 has improved a bit than previous ones. It may also have to do with my RAM which I think is 2GB even though manufacturer states 3GB.
