### ISSUE TITLE
Console.GetCursorPosition?

### ISSUE THREAD

**Issue by kirk-evans** [radimitrov/CSharpShellApp#373]
Console.SetCursorPositios works fine, but it seems that GetCursorPosition is not implemented.
Am I missing something?
Is there a workaround?

**Comment by radimitrov** [comment]
Done. It should be part of the next update.

**Comment by kirk-evans** [comment]
Thanks!

I'm new to this, so I have to ask how often do you do updates?

I really like the product.   Before I retired I was a c# programmer since
when it first came out, and Delphi before that.  It's great being able to
write apps that run on my tablet.

**Comment by radimitrov** [comment]
It's not really a schedule. On average there is 1 update every 10 days. Sometimes more often, sometimes less. Depends if there is something I'm working on. For example there are 2 updates for in last 24 hours since the first one caused an issue with the new SQLite packages versions that wasn't expected or immediately apparent. So as needed for bug fixes.
