### ISSUE TITLE
Program breaks down

### ISSUE THREAD

**Issue by anonymuspro** [radimitrov/CSharpShellApp#58]
If you close the compiler. During program execution, then at the next start, the compiler displays an error after which the entire interface in the compiler stops working and it is not possible to open the project

**Comment by radimitrov** [comment]
If you use a launcher shortcut? Yes, I get a vaguely similar issue. The app thinks it should switch to the code window and that causes problems in this scenario. I'll fix it next week,

**Comment by anonymuspro** [comment]
One more question. Could you add some hints when calling the method, just if the method takes a lot of parameters then you often

**Comment by radimitrov** [comment]
Do you mean when writing the method? It is already implemented in the top of the editor screen. 
In the code completion settings you can set it to wrap the text instead of horizontally scrolling it if that is the problem.
Or do mean with method overloads? That might be more difficult but should be doable.
![IMG_20200705_143914](https://user-images.githubusercontent.com/56889141/86531882-c6235980-becd-11ea-8ab7-3e4fb92195a3.jpg)

**Comment by anonymuspro** [comment]
I meant that it does not appear when the brackets are already open and you enter the parameters

**Comment by anonymuspro** [comment]
Suppose you need to enter 5 parameters, after the first entered above nothing is displayed

**Comment by radimitrov** [comment]
Yes. So a second popup just above where you are typing. I think it should be possible to get and show the method signature.
