### ISSUE TITLE
request for improvement

### ISSUE THREAD

**Issue by xahgo** [radimitrov/CSharpShellApp#59]
Hello. It is being used very well after paid payment. We ask for some improvements. 
* If you use "Format Code" when using tab size=2, it becomes 4 spaces. 
* When you use code folding, if you open another cs file and return, it is all open again. I want the folding state to be saved. 
* In relation to the above, we hope that a document tab that enables quick movement between cs files will be supported. 
* `if() {`
` } ` 
When coding "Format Code" above, I want the parentheses to be maintained. 
Since it is a mobile screen, I want to see as much code as possible on a narrow screen.
Thank you.

**Comment by radimitrov** [comment]
Code format easy. I'll just pass on the parameter.
Code folding should be saved. Must be a bug. I'll fix it.
There is a quickbar option for project files. Disabled by default because I don't think it justifies the reduced screen space.

You mean you want the "Format code" option to use
`if() {`
`}`
instead of
`if()`
`{`
`}`

Yes, makes sence. For screen space, at least. The formatter should support that.  I'll add an option for that if it does.

**Comment by radimitrov** [comment]
Implemented and fixed.
