### ISSUE TITLE
Environment.Exit() simply disables the app

### ISSUE THREAD

**Issue by ANF-Studios** [radimitrov/CSharpShellApp#63]
I was working on a Console App and wanted to add **Environment.Exit**, which closes the app, but in this case, it simply disabled the functionality of the app (same for **return;**).

**Comment by radimitrov** [comment]
Yes, it does exactly what it says [here](https://docs.microsoft.com/en-us/dotnet/api/system.environment.exit).
And since C# Shell and Android apps in general run in a single process - the whole app is basically killed.

But this woudn't work as expected even if you export as an individual app. You would need to "Finish" the activity and/or call "Java.Lang.JavaSystem.Exit()"
