### ISSUE TITLE
Issue with app freezing

### ISSUE THREAD

**Issue by csharpchico** [radimitrov/CSharpShellApp#70]
App freezes when switching between Class files. Says that it loaded an empty string, loads the class file but can't edit

**Comment by radimitrov** [comment]
Doesn't seem to freeze at all. 
Does this happen every time, sometimes or after a specific sequence of actions?
Can you attach a video and the settings?

**Comment by csharpchico** [comment]
![Uploading Screenshot_20201019-134607_C# Shell (C# Offline Compiler).jpg…]()

**Comment by csharpchico** [comment]
![Uploading Screenshot_20201019-134817_C# Shell (C# Offline Compiler).jpg…]()

**Comment by csharpchico** [comment]
![Uploading Screenshot_20201019-134846_C# Shell (C# Offline Compiler).jpg…]()

**Comment by csharpchico** [comment]
![Uploading Screenshot_20201019-134853_C# Shell (C# Offline Compiler).jpg…]()

**Comment by radimitrov** [comment]
Uhm, this doesn't doesnt contain images. Appears to just be several links to this [issue](https://github.com/radimitrov/CSharpShellApp/issues/70).

**Comment by csharpchico** [comment]
https://drive.google.com/file/d/1Ut-0m6MPQv8hqnGK24YeSEzDzsMEpXsf/view?usp=drivesdk

**Comment by csharpchico** [comment]
By the way this is on android 10 if that helps any

**Comment by radimitrov** [comment]
Android 10 doesn't seem to be the problem. Works in an emulator, at least.

The video shows some stuff, though. Here it is detail:
The "initialising" message is fired and shown almost immediatelly after the editor loads into the WebView. In other words right after the "C#" logo dissapears. However in the video it seems to take over 5 seconds.
The menu opens smoothly. Likely no excess load on the CPU or UI thread due to some kind of operation that is stuck.
All this suggests the problem might be in the WebView/Chrome. 

You could try turning off editor hardware acceleration in the settings. 
I guess you're using Chrome as the system WebView? See if it has an update.
Clearing the app cache and data might also help. For Chrome too.

**Comment by csharpchico** [comment]
All good now,  thanks!! Another odd bit interestingly odd concept. Typically you can't use the Enum class as a constraint but you can using this app
